### ISSUE TITLE
Run "dnx web" vs IIS

### ISSUE THREAD

**Issue by malsafra** [chemitaxis/Localization.StackOverflow#1]
Hello,

I have one question please, I tried to implement your scenario on my projects and it's working only when I run website over "dnx web" from CMD only, Otherwise only default resources file would detected.

Is there any way to enable full functionality over IIS, I've just discovered you mentioned that 

>  To TEST this Solution you must use Cmd Prompt. Inside project, run "dnx web"

 Could you please explain that to me, and I'm afraid that would cause a problem to me when I want to publish this project on IIS

Thanks

**Comment by chemitaxis** [comment]
This is a problem of VS, not of IIS, ok?

**Comment by MiguelRyR** [comment]
How can I make it work without the need of running using dxn web? Or What changes shall I make so that it works in Azure? Thanks

**Comment by chemitaxis** [comment]
It works in Azure perfectly. Tested like web app.
